backend:
  name: github
  repo: serbia70/rustblog
  branch: main
  base_url: https://rustblog-ivory.vercel.app
  auth_endpoint: /api/auth

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "misc"
    label: "杂谈"
    folder: "content/articles/misc"
    create: true
    path: "{{slug}}/index"
    format: "toml-frontmatter"
    media_folder: "../../../static/img/{{slug}}"
    public_folder: "/img/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "更新日期", name: "updated", widget: "datetime", required: false }
      - { label: "描述", name: "description", widget: "string", required: false }
      - { label: "标签", name: "taxonomies.tags", widget: "list", required: false }
      - { label: "分类", name: "taxonomies.categories", widget: "list", required: false }
      - { label: "置顶权重", name: "weight", widget: "number", required: false, value_type: "int" }
      - { label: "封面图", name: "extra.cover", widget: "string", required: false }
      - { label: "全局封面路径", name: "extra.global_cover", widget: "string", required: false }
      - { label: "微信公众号链接", name: "extra.wechat_url", widget: "string", required: false }
      - { label: "显示更新提示", name: "extra.update_tip_enable", widget: "boolean", required: false, default: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "docs"
    label: "文档"
    folder: "content/articles/docs"
    create: true
    path: "{{slug}}/index"
    format: "toml-frontmatter"
    media_folder: "../../../static/img/{{slug}}"
    public_folder: "/img/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "更新日期", name: "updated", widget: "datetime", required: false }
      - { label: "描述", name: "description", widget: "string", required: false }
      - { label: "标签", name: "taxonomies.tags", widget: "list", required: false }
      - { label: "分类", name: "taxonomies.categories", widget: "list", required: false }
      - { label: "置顶权重", name: "weight", widget: "number", required: false, value_type: "int" }
      - { label: "封面图", name: "extra.cover", widget: "string", required: false }
      - { label: "全局封面路径", name: "extra.global_cover", widget: "string", required: false }
      - { label: "显示更新提示", name: "extra.update_tip_enable", widget: "boolean", required: false, default: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "页面"
    folder: "content/pages"
    create: true
    path: "{{slug}}/index"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "描述", name: "description", widget: "string", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
